"""
Configuration file for SPS Excel Pipeline
Centralize all common variables and settings
"""
import base64
from pathlib import Path
import os

# ============================================
# BASE PATHS
# ============================================

# Project root directory (now go up one level since config is in src/)
BASE_DIR = Path(__file__).parent.parent

def get_page_icon():
    """Get page icon from logo file or fallback to emoji"""
    
    # Try multiple possible logo locations
    possible_paths = [
        Path(__file__).parent.parent / "images" / "sps_logo.png",
        Path(__file__).parent.parent / "images" / "logo.png",
        Path(__file__).parent.parent / "logo.png",
        Path(__file__).parent / "images" / "sps_logo.png",
    ]
    
    for logo_path in possible_paths:
        if logo_path.exists():
            try:
                with open(logo_path, "rb") as f:
                    logo_bytes = f.read()
                    logo_base64 = base64.b64encode(logo_bytes).decode()
                    return f"data:image/png;base64,{logo_base64}"
            except Exception:
                continue
    
    # Fallback to emoji if no logo found
    return ""

# Data directories
DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"
REPORTS_DIR = BASE_DIR / "reports"
LOGS_DIR = BASE_DIR / "logs"

# Source directory
SRC_DIR = BASE_DIR / "src"

# ============================================
# FILE SETTINGS
# ============================================

# Allowed file extensions for upload
ALLOWED_EXTENSIONS = {'.xlsx', '.xls'}

# Maximum file upload size (in MB)
MAX_UPLOAD_SIZE_MB = 200

# Sheet name patterns for detection
HIGH_LEVEL_METRICS_PATTERNS = [
    'high_level_metrics',
    'high level metrics', 
    'high-level metrics',
    'kpi',
    'dashboard',
    'summary',
    'overview'
]

# ============================================
# DASHBOARD SETTINGS
# ============================================

# Streamlit page configuration
PAGE_TITLE = "SPS Board Dashboard"
PAGE_ICON = get_page_icon()
PAGE_LAYOUT = "wide"
SIDEBAR_STATE = "expanded"

# Chart settings
CHART_HEIGHT = 600
CHART_WIDTH = 1000
CHART_TEMPLATE = 'plotly_white'

# PDF Report settings
PDF_ORIENTATION = 'L'  # Landscape
PDF_UNIT = 'mm'
PDF_FORMAT = 'A4'
PDF_MARGIN = 10

# Header colors
HEADER_COLOR = (102, 126, 234)  # Purple
KPI_SHEET_HEADER_COLOR = (155, 89, 182)  # Dark Purple
DATA_SHEET_HEADER_COLOR = (52, 152, 219)  # Blue

# Footer text
FOOTER_TEXT = "Generated by SPS Excel Pipeline | Confidential"

# KPI color mapping
KPI_COLORS = {
    'volume': (52, 152, 219),   # Blue
    'value': (46, 204, 113),    # Green
    'failed': (231, 76, 60),    # Red
    'rate': (155, 89, 182),     # Purple
    'default': (52, 152, 219)   # Default Blue
}

# ============================================
# COLUMN DETECTION KEYWORDS
# ============================================

# For value/amount columns
VALUE_COLUMN_KEYWORDS = [
    'value','VALUE', 'amount','AMOUNT', 'total', 'price', 'paymen_value', 'PAYMENT_VALUE',
    'revenue', 'fee', 'cost', 'sum', 
    'sales', 'transaction_value'
]

# For volume/count columns
VOLUME_COLUMN_KEYWORDS = [
    'volume','VOLUME', 'count', 'qty', 'quantity','payment_volume', 'PAYMENT_VOLUME',
    'number', 'total_count', 'transaction_count'
]

# For status columns
STATUS_COLUMN_KEYWORDS = [
    'status', 'state', 'result', 'outcome', 
    'transaction_status', 'type'
]

# For date columns
DATE_COLUMN_KEYWORDS = [
    'date', 'time', 'created', 'updated', 
    'timestamp', 'transaction_date', 'entry_date'
]

# For category columns
CATEGORY_COLUMN_KEYWORDS = [
    'category', 'type', 'group', 'class',
    'region', 'department', 'product'
]

# ============================================
# SUCCESS/FAILURE DETECTION KEYWORDS
# ============================================

SUCCESS_KEYWORDS = [
    'success', 'succeeded', 'completed', 
    'approved', 'done', 'pass', 'active', 
    '1', 'true', 'yes'
]

FAILURE_KEYWORDS = [
    'failed', 'fail', 'error', 'declined', 
    'rejected', 'cancelled', 'void', 
    '0', 'false', 'no'
]

PENDING_KEYWORDS = [
    'pending', 'waiting', 'processing', 
    'initiated', 'started'
]

# ============================================
# LOGO SETTINGS
# ============================================

LOGO_PATH = BASE_DIR / "images" / "sps_logo.png"
FALLBACK_LOGO_URL = "https://img.icons8.com/fluency/96/data-configuration.png"

# ============================================
# TRANSACTION RULES CONFIGURATION
# ============================================

# Predefined rules for transaction filtering
TRANSACTION_RULES = {
    # Rule Code: Rule Name
    '1009': '3DS_01',
    '1010': '3DS_02_01',
    '1011': '3DS_02_02',
    '1012': '3DS_03',
    '1013': '3DS_04_01',
    '1014': '3DS_04_02',
    '1015': 'Limit exceeded control',
    '1016': 'Limit control blocked and transfer',
    '1017': 'Count & amount long interval',
    '1018': 'Max TXN amount',
    '1019': 'Suspicious Account List',
    '1020': 'Count & amount progressive time',
    '1021': 'Demo1',
    '1022': 'Transactions, amount, and time',
    '1023': 'Demo 3',
    '1024': 'Demo 2',
    '1025': 'Count & amount short interval',
    '1026': 'Limit control of 80%',
    '1027': 'Transaction amount 10K (Sender)',
    '1028': 'Transaction amount 10K (Receiver)',
    '1029': 'SPS Blocked Senders',
    '1030': 'SPS Blocked Receivers',
    '1031': 'CBS Blocked Receivers',
    '1032': 'CBS Blocked Senders',
    '1033': 'OFAC Blocked Senders',
    '1034': 'OFAC Blocked Receivers',
}

# Rule categories for better organization
RULE_CATEGORIES = {
    ' Risk Level': [
        ('1019', 'Suspicious Account List'),
        ('1029', 'SPS Blocked Senders'),
        ('1030', 'SPS Blocked Receivers'),
        ('1031', 'CBS Blocked Receivers'),
        ('1032', 'CBS Blocked Senders'),
        ('1033', 'OFAC Blocked Senders'),
        ('1034', 'OFAC Blocked Receivers'),
    ],
    ' Amount Limits': [
        ('1015', 'Limit exceeded control'),
        ('1016', 'Limit control blocked and transfer'),
        ('1018', 'Max TXN amount'),
        ('1026', 'Limit control of 80%'),
        ('1027', 'Transaction amount 10K (Sender)'),
        ('1028', 'Transaction amount 10K (Receiver)'),
    ],
    ' 3DS Verification': [
        ('1009', '3DS_01'),
        ('1010', '3DS_02_01'),
        ('1011', '3DS_02_02'),
        ('1012', '3DS_03'),
        ('1013', '3DS_04_01'),
        ('1014', '3DS_04_02'),
    ],
    ' Time & Count': [
        ('1017', 'Count & amount long interval'),
        ('1020', 'Count & amount progressive time'),
        ('1025', 'Count & amount short interval'),
        ('1022', 'Transactions, amount, and time'),
    ],
    ' Demo': [
        ('1021', 'Demo1'),
        ('1023', 'Demo 3'),
        ('1024', 'Demo 2'),
    ],
}

# ============================================
# UTILITY FUNCTIONS
# ============================================

def ensure_directories():
    """Create all necessary directories if they don't exist"""
    directories = [
        DATA_DIR,
        RAW_DIR,
        PROCESSED_DIR,
        REPORTS_DIR,
        LOGS_DIR
    ]
    
    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)
    
    return True


def get_config_summary() -> dict:
    """Return a summary of current configuration"""
    return {
        'base_dir': str(BASE_DIR),
        'data_dir': str(DATA_DIR),
        'raw_dir': str(RAW_DIR),
        'processed_dir': str(PROCESSED_DIR),
        'reports_dir': str(REPORTS_DIR),
        'max_upload_size_mb': MAX_UPLOAD_SIZE_MB,
        'allowed_extensions': list(ALLOWED_EXTENSIONS),
        'page_title': PAGE_TITLE,
        'chart_template': CHART_TEMPLATE,
        'pdf_format': PDF_FORMAT,
        'total_rules': len(TRANSACTION_RULES)
    }


def get_rule_name(rule_code: str) -> str:
    """Get rule name from rule code"""
    return TRANSACTION_RULES.get(str(rule_code), rule_code)


def get_rule_code(rule_name: str) -> str:
    """Get rule code from rule name"""
    for code, name in TRANSACTION_RULES.items():
        if name == rule_name:
            return code
    return rule_name


def get_all_rule_names() -> list:
    """Get all rule names sorted"""
    return sorted(TRANSACTION_RULES.values())


def get_all_rule_codes() -> list:
    """Get all rule codes sorted"""
    return sorted(TRANSACTION_RULES.keys())


def get_rules_by_category(category: str = None) -> dict:
    """Get rules grouped by category"""
    if category:
        return dict(RULE_CATEGORIES.get(category, []))
    return RULE_CATEGORIES


# # ============================================
# # ENVIRONMENT VARIABLES (Optional)
# # ============================================

# # API Settings (from .env file)
# API_KEY = os.getenv('API_KEY', '')
# API_SECRET = os.getenv('API_SECRET', '')
# ENABLE_EXTERNAL_API = os.getenv('ENABLE_EXTERNAL_API', 'false').lower() == 'true'
# DEBUG_MODE = os.getenv('DEBUG_MODE', 'false').lower() == 'true'